services:
  - docker

language: node_js
node_js:
 - "lts/*"

stages:
  - test
  - name: build-deploy
    if: branch = master

jobs:
  include:
    - stage: test
      script: 
        - npm run test
      name: "Tests"

    - stage: build-deploy
      script: 
        - bash scripts/build-deploy.sh
      name: "Build and Push Docker image"