services:
  - docker

language: node_js
node_js:
 - "lts/*"

stages:
  - test
  - name: build-deploy
    if: branch = master

jobs:
  include:
    - stage: test
      script: 
        - npm run test
      name: "Tests"

    - stage: build-deploy
      script: 
        - docker build -t nookazon-helper .
        - docker images
        - docker tag nookazon-helper $DOCKER_USERNAME/nookazon-helper
        - echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
        - docker push $DOCKER_USERNAME/nookazon-helper
      name: "Build and Push Docker image"