sudo: required

services:
  - docker

language: node_js
node_js:
 - "lts/*"

cache:
  directories:
    - node_modules

stages:
  - test
  - name: build
    if: branch = master
  - name: deploy
    if: branch = master

jobs:
  include:
    - stage: test
      script: 
      - npm run test
      name: "Tests"

    - stage: build
      script: 
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker build -t nookazon-helper .
      name: "Build Docker image"

    - stage: upload
      script:
      - docker images
      - docker tag nookazon-helper $DOCKER_USERNAME/nookazon-helper
      - docker push $DOCKER_USERNAME/nookazon-helper
      name: "Push Docker image to repo"