version: '3.0'
services:
  discord-bot:
    image: sudomac/nookazon-helper:latest
    depends_on:
      - mariadb
    environment:
      DISCORD_TOKEN: 'fill-me-in'
      COMMAND_PREFIX: 'fill-me-in'
      DBHOST: mariadb
      DBUSER: nook
      DBPASS: 'fill-me-in'
      DBNAME: nookazon
    logging:
      driver: json-file
      options:
        tag: "{{.DaemonName}}(image={{.ImageName}};name={{.Name}};id={{.ID}})"
  mariadb:
    image: mariadb:10.2
    environment:
      MYSQL_ROOT_PASSWORD: 'fill-me-in'
      MYSQL_DATABASE: nookazon
      MYSQL_USER: nook
      MYSQL_PASSWORD: 'fill-me-in'
    logging:
      driver: json-file
      options:
        tag: "{{.DaemonName}}(image={{.ImageName}};name={{.Name}};id={{.ID}})"
    restart: on-failure
    volumes:
      - db_data:/var/lib/mysql
      - ./src/utils/database/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
volumes:
 db_data: